### ISSUE TITLE
enhancement: the API white list on shopifyApiProxy should be extended

### ISSUE THREAD

**Issue by gregorybesson** [Shopify/shopify-express#16]
For now, only the following endpoints are listed in the white list:
`ALLOWED_URLS = ['/products', '/orders'];`

We should add all the api endpoints, as these endpoints are secured and you can't access them without a proper authorization from the shop owner.

Am I mistaken here ?

;)
Greg

**Comment by AWaselnuk** [comment]
Yes at the minimum we should make this whitelist optional. @kevinhughes27 @TheMallen do either of you remember why we introduced the whitelist in the first place?

**Comment by kevinhughes27** [comment]
I'm not sure why we added the whitelist, maybe to create a dropdown with all possible requests?

**Comment by TheMallen** [comment]
I think I added it way back when during like ux summit or something, don't remember why.

**Comment by AWaselnuk** [comment]
Alright then seems like we can probably just drop the whitelist entirely as suggested by @gregorybesson. (same effect as adding every single endpoint)

**Comment by jamiemtdwyer** [comment]
One reason for not dropping the whitelist would be that you wouldn't want the client calling into any of the billing endpoints – e.g. `/admin/application_charges.json`, `/admin/recurring_application_charges.json` and destroying the application charge.

Maybe a blacklist specifically on the billing endpoints would make more sense.

**Comment by TheMallen** [comment]
that makes sense to me, but we should note that it would also need the scopes for that, no?

**Comment by jamiemtdwyer** [comment]
There aren't any specific scopes for accessing the billing endpoints, they are accessible by any API permission.

**Comment by gregorybesson** [comment]
@jamiemtdwyer if it's the case, it has to be solved on the API side, not on the client side I think. The billing endpoints should have their proper scopes, no ?

Removing the whitelist seems to me the best option

**Comment by jamiemtdwyer** [comment]
I don't believe scoping at an API level is the issue here – if scoping were added at the API level, the API client itself would not be able to create application charges which is not the intended restriction here. The intended restriction of any sort of "whitelist" or "blacklist" in the API proxy would be intended to prevent the _client_ itself from accessing any restricted endpoints.

**Comment by TheMallen** [comment]
Yeah @jamiemtdwyer is spot on. I think we can either use a blacklist, or let the app pass in a whitelist of their own.

**Comment by jamiemtdwyer** [comment]
Here's a quick and dirty list of what I think should be included in such a blacklist:

* /admin/application_charges.json
* /admin/application_credits.json
* /admin/carrier_services.json
* /admin/recurring_application_charges.json
* /admin/script_tags.json
* /admin/storefront_access_token.json
* /admin/webhooks.json
* /admin/oauth & any of its sub-routes

Basically, any of the billing endpoints (prevent the client from destroying application charges or creating application charge credits), anything that would interfere with authentication, and anything that could interfere with the configuration of the application (webhooks, script tags et al).

**Comment by TheMallen** [comment]
And then if the app wants to make requests to these they just have to roll their own endpoints 👍

**Comment by acebytes** [comment]
Hi, thank you for making this code available. I'm attempting to use this project as a dependency for an embedded app that needs to call the script tag API endpoint. Because of the included endpoint blacklist, am I correct in assuming I need to edit shopifyApiProxy.js in order to utilize the middleware included in this project?

The DISALLOWED_URLS array is hard-coded into the `validRequest()` function, with no way to pass in a custom replacement without editing the array or the function.

Please correct me if my conclusion is not correct.

```
function validRequest(path) {
  const strippedPath = path.split('?')[0].split('.json')[0];

  return DISALLOWED_URLS.every(resource => {
    return strippedPath.indexOf(resource) === -1;
  });
}
```

**Comment by jamiemtdwyer** [comment]
Hm, yeah the blacklist should probably be configurable in some way.
