### ISSUE TITLE
Getting 403 on Heroku Redis only on Carrier Services endpoint

### ISSUE THREAD

**Issue by buyandfly7** [Shopify/shopify-express#79]
Deployed and launched to Heroku successfully, works good with all endpoints but
Getting 403 when trying to access `carrier_services.json` or `fulfillment` endpoints

What can be the problem? Tested locally with ngrok, the same issue

p.s.
scope is correct

**Comment by buyandfly7** [comment]
found it in DISALLOWED_URLS, what is the correct way to reach these endpoints?

**Comment by jamiemtdwyer** [comment]
You can either choose to remove them from the blacklist so that they are
accessible through the API proxy or create your own proxy route so that
these calls are accessible via AJAX.

Alternatively, you can access these Shopify API endpoints directly from the
back-end of your application - typically something like a CarrierService or
FulfillmentService would be configured automatically by your application
after the app is installed.

The logic for blacklisting these routes by default is to prevent the user
from potentially altering any configuration that might prevent the app from
working as intended. It's not necessarily dangerous to remove these
endpoints from the blacklist.

Hope this helps.

**Comment by buyandfly7** [comment]
Тhanks, accessed from backend. Works fine.
